language: java
jdk: openjdk8

install: skip

before_script: chmod +x ./gradlew           # Get Permissions
script: ./gradlew jar test clean            # Compile, Test, Clean excluding .jar

branches:
  only:
    - master                           # master
    - /(feature/).*/                   # for features
    - /[0-9]+\.[0-9]+\.[0-9]+(.*)?/    # TAG

before_deploy:                         # Create Archive
# - rm -fr build/classes/              # Uncomment line if used ant for buld
 - mkdir build/jar
 - ln build/libs/apk-dependency-graph.jar build/jar/apk-dependency-graph.jar
 - zip -r apk-dependency-graph-scripts-$TRAVIS_TAG.zip build/jar/apk-dependency-graph.jar gui/ filters/ run.bat run.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN               # More options > Settings > Environment Variables
  skip_cleanup: true
  file: apk-dependency-graph-scripts-$TRAVIS_TAG.zip
  name: $TRAVIS_TAG
  on:
    branch: master
    tags: true
